---
title: "timeline"
format: html
---

```{r setup}
#| warning: false

# Loading libraries
library(readxl)
library(tidyverse)
library(ggthemes)
library(scales)
```

```{r tl}
# Reading data in
tl <- read_excel("../data/timeline.xlsx")

```

```{r wrangle}
# Gathering dates
tl_w <- tl %>% 
  pivot_longer(cols = start:end, 
               names_to = "datetype",
               values_to = "value"
               ) %>%
# Inverting levels
  mutate(name=factor(name),
         name=fct_reorder(name, -eventnum)) %>%
  mutate(value=as.Date(value),
         type=factor(type,
                     levels = c("data",
                                "analysis",
                                "report")))

```

```{r}
ggplot(tl_w, aes(x = value, 
                 y = name, 
                 colour = type)) + 
  geom_line(size = 6, show.legend = T) +
  labs(title = "Cotton Quality Meta-analysis Timeline",
       x = NULL,
       y = NULL)+
  scale_x_date(limits = c((min(tl_w$value)-30),
                          (max(tl_w$value)+15)), 
               labels = date_format("%b %y"), 
               breaks = date_breaks("2 months"),
               minor_breaks = date_breaks("year"))+
  scale_color_viridis_d()+
  theme_bw()+
  theme(legend.title=element_blank(), 
        legend.position=c(.85,.7),
        legend.background = element_rect(color="black", 
                                         size=.1),
        plot.title = element_text(hjust = .5),
        panel.grid.minor.x = element_line(linetype=2, 
                                          size=.5, 
                                          color="black"),
        axis.text.x = element_text(hjust = 1, angle = 20)
        )

ggsave("../output/timeline.png",
       width = 6,
       height = 3)
```
